name: poultry_admin_panel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


    # Utility packages
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  cached_network_image: ^3.4.1
  multi_select_flutter: ^4.1.3
  connectivity_plus: ^6.1.0
  flutter_dropzone: ^4.1.0
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  lottie: ^3.1.3
  image_picker: ^1.1.2
  intl: ^0.20.1
  flutter_staggered_grid_view: ^0.7.0

    # Web specific
  web: ^1.1.0
  http: ^1.2.2
  html: ^0.15.5
  fl_chart: ^0.69.0
  data_table_2: ^2.5.15
  url_strategy: ^0.3.0
  dio: ^5.7.0
  logger: ^2.4.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  dropdown_button2: ^2.3.9




  # State management
  get_storage: ^2.1.1
  get: ^4.6.6

    # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4


# Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

dev_dependencies:
   flutter_test:
     sdk: flutter

   flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.

flutter:




  uses-material-design: true


  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/logos/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/

  #-------Local fonts----#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic









