// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZHAeCtwdF79bGFUpc8ecHrtUF-n8cI0',
    appId: '1:75419580201:web:2b98959c02085636c0a938',
    messagingSenderId: '75419580201',
    projectId: 'inara-4a66f',
    authDomain: 'inara-4a66f.firebaseapp.com',
    storageBucket: 'inara-4a66f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZh5HUlYG6M9mPhz4dXlPfGeSWZdLk0fQ',
    appId: '1:75419580201:android:9884b8fecb8796e0c0a938',
    messagingSenderId: '75419580201',
    projectId: 'inara-4a66f',
    storageBucket: 'inara-4a66f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNVXd4onFstRlfi8ho86scXtjkUvoVwHU',
    appId: '1:75419580201:ios:36fa4faa9691705dc0a938',
    messagingSenderId: '75419580201',
    projectId: 'inara-4a66f',
    storageBucket: 'inara-4a66f.firebasestorage.app',
    iosBundleId: 'com.example.poultryAdminPanel',
  );
}
